/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formatmytxts;

import java.awt.Component;
import java.io.File;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author root
 */
public class FormatMyTxt_Frame extends javax.swing.JFrame {

    /**
     * Creates new form FormatMyTxt_Frame
     */
    public FormatMyTxt_Frame() {
        initComponents();
        this.jFileChooser1.setMultiSelectionEnabled(true);
        this.counter = new AtomicInteger(0);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jCheckBox7 = new javax.swing.JCheckBox();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        jFileChooser1.setAcceptAllFileFilterUsed(false);
        jFileChooser1.setApproveButtonText("SELECT");
        jFileChooser1.setCurrentDirectory(new java.io.File("/home/isaac/Documentos/git/AguaEnMexico/Resumenes-Mensuales-de-precipitacion"));
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Plain text files", "txt"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Format my txts 1.0");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setText("Load files...");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton9.setText("Apply and save");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton9MouseReleased(evt);
            }
        });
        jPanel2.add(jButton9);

        jCheckBox7.setText("Save as...");
        jCheckBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckBox7MouseReleased(evt);
            }
        });
        jPanel2.add(jCheckBox7);

        jTextField5.setEnabled(false);
        jTextField5.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel2.add(jTextField5);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox1.setText("Delete all..");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseReleased(evt);
            }
        });
        jPanel3.add(jCheckBox1);

        jRadioButton4.setSelected(true);
        jRadioButton4.setText("before");
        jRadioButton4.setEnabled(false);
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseReleased(evt);
            }
        });
        jPanel3.add(jRadioButton4);

        jRadioButton5.setText("after");
        jRadioButton5.setEnabled(false);
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton5MouseReleased(evt);
            }
        });
        jPanel3.add(jRadioButton5);

        jTextField4.setEnabled(false);
        jTextField4.setPreferredSize(new java.awt.Dimension(220, 30));
        jPanel3.add(jTextField4);

        jPanel1.add(jPanel3);

        jPanel7.setMinimumSize(new java.awt.Dimension(132, 35));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox4.setText("Replace:");
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseReleased(evt);
            }
        });
        jPanel7.add(jCheckBox4);

        jTextField2.setEnabled(false);
        jTextField2.setPreferredSize(new java.awt.Dimension(165, 30));
        jPanel7.add(jTextField2);

        jLabel4.setText("with:");
        jPanel7.add(jLabel4);

        jTextField3.setEnabled(false);
        jTextField3.setPreferredSize(new java.awt.Dimension(165, 30));
        jPanel7.add(jTextField3);

        jPanel1.add(jPanel7);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox2.setText("Normalize by...");
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseReleased(evt);
            }
        });
        jPanel5.add(jCheckBox2);

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("space");
        jRadioButton1.setEnabled(false);
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseReleased(evt);
            }
        });
        jPanel5.add(jRadioButton1);

        jRadioButton2.setText("tab");
        jRadioButton2.setEnabled(false);
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseReleased(evt);
            }
        });
        jPanel5.add(jRadioButton2);

        jRadioButton3.setText("NewLine");
        jRadioButton3.setEnabled(false);
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseReleased(evt);
            }
        });
        jPanel5.add(jRadioButton3);

        jRadioButton8.setText("Go ASCII");
        jRadioButton8.setEnabled(false);
        jRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton8MouseReleased(evt);
            }
        });
        jPanel5.add(jRadioButton8);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox3.setText("Group data in");
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseReleased(evt);
            }
        });
        jPanel6.add(jCheckBox3);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000000, 1));
        jSpinner1.setEnabled(false);
        jSpinner1.setPreferredSize(new java.awt.Dimension(70, 25));
        jPanel6.add(jSpinner1);

        jLabel2.setText("Separated by:");
        jPanel6.add(jLabel2);

        jTextField1.setEnabled(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel6.add(jTextField1);

        jPanel1.add(jPanel6);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jCheckBox5.setText("Upper-case...");
        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseReleased(evt);
            }
        });
        jPanel4.add(jCheckBox5);

        jRadioButton6.setSelected(true);
        jRadioButton6.setText("ALL");
        jRadioButton6.setEnabled(false);
        jRadioButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton6MouseReleased(evt);
            }
        });
        jPanel4.add(jRadioButton6);

        jRadioButton7.setText("none");
        jRadioButton7.setEnabled(false);
        jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton7MouseReleased(evt);
            }
        });
        jPanel4.add(jRadioButton7);

        jRadioButton9.setText("First");
        jRadioButton9.setEnabled(false);
        jRadioButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jRadioButton9MouseReleased(evt);
            }
        });
        jPanel4.add(jRadioButton9);

        jPanel1.add(jPanel4);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jProgressBar1.setToolTipText("Completed: 0");
        jProgressBar1.setStringPainted(true);
        jPanel8.add(jProgressBar1);

        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseReleased
        if(this.jCheckBox5.isSelected())
            recursivelyDisableComponents((JComponent) this.jCheckBox5.getParent(), true);
        else
        {
            recursivelyDisableComponents((JComponent) this.jCheckBox5.getParent(), false);
            this.jCheckBox5.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox5MouseReleased

    private void jCheckBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseReleased
        if(this.jCheckBox1.isSelected())
            recursivelyDisableComponents((JComponent) this.jCheckBox1.getParent(), true);
        else
        {
            recursivelyDisableComponents((JComponent) this.jCheckBox1.getParent(), false);
            this.jCheckBox1.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox1MouseReleased

    private void jCheckBox2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseReleased
        if(this.jCheckBox2.isSelected())
            recursivelyDisableComponents((JComponent) this.jCheckBox2.getParent(), true);
        else
        {
            recursivelyDisableComponents((JComponent) this.jCheckBox2.getParent(), false);
            this.jCheckBox2.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox2MouseReleased

    private void jCheckBox3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseReleased
        if(this.jCheckBox3.isSelected())
            recursivelyDisableComponents((JComponent) this.jCheckBox3.getParent(), true);
        else
        {
            recursivelyDisableComponents((JComponent) this.jCheckBox3.getParent(), false);
            this.jCheckBox3.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox3MouseReleased

    private void jCheckBox4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseReleased
        if(this.jCheckBox4.isSelected())
            recursivelyDisableComponents((JComponent) this.jCheckBox4.getParent(), true);
        else
        {
            recursivelyDisableComponents((JComponent) this.jCheckBox4.getParent(), false);
            this.jCheckBox4.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox4MouseReleased

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        
        if( this.jFileChooser1.showOpenDialog(jPanel2) != JFileChooser.APPROVE_OPTION)
            return;
        else
        {
            this.counter.set(0);
            this.jProgressBar1.setValue(0);
        }
        
        
    }//GEN-LAST:event_jButton1MouseReleased

    private void jRadioButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton6MouseReleased
        if(!this.jRadioButton6.isEnabled())
            return;
        
        this.jRadioButton6.setSelected(true);
        this.jRadioButton7.setSelected(false);
        this.jRadioButton9.setSelected(false);
    }//GEN-LAST:event_jRadioButton6MouseReleased

    private void jRadioButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton7MouseReleased
        if(!this.jRadioButton7.isEnabled())
            return;
        
        this.jRadioButton7.setSelected(true);
        this.jRadioButton6.setSelected(false);
        this.jRadioButton9.setSelected(false);
        
    }//GEN-LAST:event_jRadioButton7MouseReleased

    private void jRadioButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseReleased
        if(!this.jRadioButton5.isEnabled())
            return;
        
        this.jRadioButton5.setSelected(true);

        
        this.jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton5MouseReleased

    private void jRadioButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseReleased
        if(!this.jRadioButton1.isEnabled())
            return;
        
        this.jRadioButton1.setSelected(true);
        
        this.jRadioButton8.setSelected(false);
        this.jRadioButton2.setSelected(false);
        this.jRadioButton3.setSelected(false);    }//GEN-LAST:event_jRadioButton1MouseReleased

    private void jRadioButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseReleased
        if(!this.jRadioButton2.isEnabled())
            return;
        
        this.jRadioButton2.setSelected(true);

        this.jRadioButton1.setSelected(false);
        this.jRadioButton8.setSelected(false);
        this.jRadioButton3.setSelected(false);    }//GEN-LAST:event_jRadioButton2MouseReleased

    private void jRadioButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseReleased
        if(!this.jRadioButton3.isEnabled())
            return;
        this.jRadioButton3.setSelected(true);

        this.jRadioButton1.setSelected(false);
        this.jRadioButton8.setSelected(false);
        this.jRadioButton2.setSelected(false);    }//GEN-LAST:event_jRadioButton3MouseReleased

    private void jCheckBox7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox7MouseReleased
        this.jTextField5.setEnabled(this.jCheckBox7.isSelected());
    }//GEN-LAST:event_jCheckBox7MouseReleased

    private void jButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseReleased
        
        final int nFiles;

        File[] files = this.jFileChooser1.getSelectedFiles();
        
        nFiles = files.length;
        this.txtThreads = new txtFormatter[nFiles];
        int index = 0;
        
        this.counter.set(0);
        this.jProgressBar1.setValue(0);
        this.jProgressBar1.setMaximum(nFiles);
        
        for( File file : files)
        {
            this.txtThreads[index] = new txtFormatter(file);
            setChanges( this.txtThreads[index] );
            
            this.txtThreads[index].start();
            
            index++;
        }
        
    }//GEN-LAST:event_jButton9MouseReleased

    private void jRadioButton8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton8MouseReleased
        
    if(!this.jRadioButton3.isEnabled())
        return;
        
    this.jRadioButton1.setSelected(false);
    this.jRadioButton2.setSelected(false);
    this.jRadioButton3.setSelected(false);
    
    this.jRadioButton8.setSelected(true);

    }//GEN-LAST:event_jRadioButton8MouseReleased

    private void jRadioButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseReleased

    if(!this.jRadioButton4.isEnabled())
        return;
        
    this.jRadioButton5.setSelected(false);
    
    this.jRadioButton4.setSelected(true);

    }//GEN-LAST:event_jRadioButton4MouseReleased

    private void jRadioButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton9MouseReleased
    
        if(!this.jRadioButton9.isEnabled())
            return;

        this.jRadioButton9.setSelected(true);
        this.jRadioButton6.setSelected(false);
        this.jRadioButton7.setSelected(false);
        
    }//GEN-LAST:event_jRadioButton9MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormatMyTxt_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormatMyTxt_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormatMyTxt_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormatMyTxt_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormatMyTxt_Frame().setVisible(true);
            }
        });
    }
    
    private static void recursivelyDisableComponents(JComponent comp, boolean disEn)
    {
        synchronized(comp.getTreeLock()) {
            if(comp.getComponentCount() > 1)
                for (Component c : comp.getComponents())
                {
                    c.setEnabled(disEn);
                    recursivelyDisableComponents((JComponent)c, disEn);
                }
        }
    }
    
    private void setChanges(txtFormatter currentOne)
    {
        currentOne.setProgress(this.jProgressBar1);
        currentOne.setCounter(counter);
        
        if(this.jCheckBox1.isSelected())
        {
                currentOne.setWillDelete(true);
                currentOne.setDeleteBefore( this.jRadioButton4.isSelected() );
                currentOne.setDelete( this.jTextField4.getText() );
        }
        
        if(this.jCheckBox2.isSelected())
        {
            currentOne.setWillNormalize( true );
            
            if( this.jRadioButton1.isSelected() )
                currentOne.setNormalize(" ");
            else if( this.jRadioButton2.isSelected() )
                currentOne.setNormalize("\t");
            else if( this.jRadioButton3.isSelected() )
                currentOne.setNormalize("\n");
            else if( this.jRadioButton8.isSelected() )
                currentOne.setNormalize("ANSI");
        }
        
        if(this.jCheckBox3.isSelected())
        {
                currentOne.setWillGroup(true);
                currentOne.setGroup( (Integer)this.jSpinner1.getValue() );
                currentOne.setSeparator( this.jTextField1.getText() );
        }
        
        if(this.jCheckBox4.isSelected())
        {
                currentOne.setWillReplace(true);
                currentOne.setReplace( this.jTextField2.getText() );
                currentOne.setWith( this.jTextField3.getText() );
        }
        
        if(this.jCheckBox5.isSelected())
        {
                currentOne.setWillCase(true);
                
                int caseMode = -1;
                
                caseMode = this.jRadioButton6.isSelected() ? 0 : caseMode;
                caseMode = this.jRadioButton7.isSelected() ? 1 : caseMode;
                caseMode = this.jRadioButton9.isSelected() ? 2 : caseMode;
                
                currentOne.setCaseMode( caseMode );
                currentOne.setCaseMode( caseMode );
                currentOne.setCaseMode( caseMode );
                
        }
        
        if(this.jCheckBox7.isSelected())
        {
            currentOne.setWillSaveAs(true);
            currentOne.setSaveAs( this.jTextField5.getText() );
        }
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
    
    private txtFormatter[] txtThreads;
    private AtomicInteger counter;
}
